//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfaceLib.SSOService
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://service.ws.accela.com")]
    public interface SSO
    {

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults = true, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "signon4WSReturn")]
        InterfaceLib.SSOService.UserSessionImpl4WS signon4WS(string systemID, string domain, string agencyID, string userID, string password);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults = true, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "signonReturn")]
        string signon(string agencyID, string userId, string password);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults = true, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "authenticateReturn")]
        string authenticate(string userId, string ssoSessionId);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://model.ws.accela.com")]
    public partial class UserSessionImpl4WS : object, System.ComponentModel.INotifyPropertyChanged
    {

        private SessionImpl sessionField;

        private System.Nullable<System.DateTime> sessionCreateTimeField;

        private System.Nullable<System.DateTime> sessionExpireTimeField;

        private bool sessionExpiredField;

        private string sessionIdField;

        private System.Nullable<System.DateTime> sessionLastAccessTimeField;

        private UserImpl userField;

        private string userCommonNameField;

        private string userDistinguishedNameField;

        private string userDomainField;

        private string userIdField;

        private string userOrganizationIdField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public SessionImpl session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
                this.RaisePropertyChanged("session");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> sessionCreateTime
        {
            get
            {
                return this.sessionCreateTimeField;
            }
            set
            {
                this.sessionCreateTimeField = value;
                this.RaisePropertyChanged("sessionCreateTime");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> sessionExpireTime
        {
            get
            {
                return this.sessionExpireTimeField;
            }
            set
            {
                this.sessionExpireTimeField = value;
                this.RaisePropertyChanged("sessionExpireTime");
            }
        }

        /// <remarks/>
        public bool sessionExpired
        {
            get
            {
                return this.sessionExpiredField;
            }
            set
            {
                this.sessionExpiredField = value;
                this.RaisePropertyChanged("sessionExpired");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string sessionId
        {
            get
            {
                return this.sessionIdField;
            }
            set
            {
                this.sessionIdField = value;
                this.RaisePropertyChanged("sessionId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> sessionLastAccessTime
        {
            get
            {
                return this.sessionLastAccessTimeField;
            }
            set
            {
                this.sessionLastAccessTimeField = value;
                this.RaisePropertyChanged("sessionLastAccessTime");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public UserImpl user
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string userCommonName
        {
            get
            {
                return this.userCommonNameField;
            }
            set
            {
                this.userCommonNameField = value;
                this.RaisePropertyChanged("userCommonName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string userDistinguishedName
        {
            get
            {
                return this.userDistinguishedNameField;
            }
            set
            {
                this.userDistinguishedNameField = value;
                this.RaisePropertyChanged("userDistinguishedName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string userDomain
        {
            get
            {
                return this.userDomainField;
            }
            set
            {
                this.userDomainField = value;
                this.RaisePropertyChanged("userDomain");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string userOrganizationId
        {
            get
            {
                return this.userOrganizationIdField;
            }
            set
            {
                this.userOrganizationIdField = value;
                this.RaisePropertyChanged("userOrganizationId");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://security.accela.com")]
    public partial class SessionImpl : object, System.ComponentModel.INotifyPropertyChanged
    {

        private System.Nullable<System.DateTime> createTimeField;

        private System.Nullable<System.DateTime> expireTimeField;

        private bool expiredField;

        private System.Nullable<System.DateTime> lastAccessTimeField;

        private string sessionIdField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> createTime
        {
            get
            {
                return this.createTimeField;
            }
            set
            {
                this.createTimeField = value;
                this.RaisePropertyChanged("createTime");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> expireTime
        {
            get
            {
                return this.expireTimeField;
            }
            set
            {
                this.expireTimeField = value;
                this.RaisePropertyChanged("expireTime");
            }
        }

        /// <remarks/>
        public bool expired
        {
            get
            {
                return this.expiredField;
            }
            set
            {
                this.expiredField = value;
                this.RaisePropertyChanged("expired");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> lastAccessTime
        {
            get
            {
                return this.lastAccessTimeField;
            }
            set
            {
                this.lastAccessTimeField = value;
                this.RaisePropertyChanged("lastAccessTime");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string sessionId
        {
            get
            {
                return this.sessionIdField;
            }
            set
            {
                this.sessionIdField = value;
                this.RaisePropertyChanged("sessionId");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://security.accela.com")]
    public partial class UserImpl : object, System.ComponentModel.INotifyPropertyChanged
    {

        private bool activeField;

        private string commonNameField;

        private string distinguishedNameField;

        private string distinguishedName4DisplayField;

        private string distinguishedName4SearchField;

        private string domainField;

        private string employeeIdField;

        private string firstNameField;

        private string integratedFlagField;

        private string lastNameField;

        private string mailField;

        private string middleNameField;

        private string organizationIdField;

        private string titleField;

        private string userIdField;

        /// <remarks/>
        public bool active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
                this.RaisePropertyChanged("active");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string commonName
        {
            get
            {
                return this.commonNameField;
            }
            set
            {
                this.commonNameField = value;
                this.RaisePropertyChanged("commonName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string distinguishedName
        {
            get
            {
                return this.distinguishedNameField;
            }
            set
            {
                this.distinguishedNameField = value;
                this.RaisePropertyChanged("distinguishedName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string distinguishedName4Display
        {
            get
            {
                return this.distinguishedName4DisplayField;
            }
            set
            {
                this.distinguishedName4DisplayField = value;
                this.RaisePropertyChanged("distinguishedName4Display");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string distinguishedName4Search
        {
            get
            {
                return this.distinguishedName4SearchField;
            }
            set
            {
                this.distinguishedName4SearchField = value;
                this.RaisePropertyChanged("distinguishedName4Search");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string domain
        {
            get
            {
                return this.domainField;
            }
            set
            {
                this.domainField = value;
                this.RaisePropertyChanged("domain");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string employeeId
        {
            get
            {
                return this.employeeIdField;
            }
            set
            {
                this.employeeIdField = value;
                this.RaisePropertyChanged("employeeId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
                this.RaisePropertyChanged("firstName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string integratedFlag
        {
            get
            {
                return this.integratedFlagField;
            }
            set
            {
                this.integratedFlagField = value;
                this.RaisePropertyChanged("integratedFlag");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
                this.RaisePropertyChanged("lastName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string mail
        {
            get
            {
                return this.mailField;
            }
            set
            {
                this.mailField = value;
                this.RaisePropertyChanged("mail");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string middleName
        {
            get
            {
                return this.middleNameField;
            }
            set
            {
                this.middleNameField = value;
                this.RaisePropertyChanged("middleName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string organizationId
        {
            get
            {
                return this.organizationIdField;
            }
            set
            {
                this.organizationIdField = value;
                this.RaisePropertyChanged("organizationId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SSOChannel : InterfaceLib.SSOService.SSO, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SSOClient : System.ServiceModel.ClientBase<InterfaceLib.SSOService.SSO>, InterfaceLib.SSOService.SSO
    {

        public SSOClient()
        {
        }

        public SSOClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public SSOClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public SSOClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public SSOClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public InterfaceLib.SSOService.UserSessionImpl4WS signon4WS(string systemID, string domain, string agencyID, string userID, string password)
        {
            return base.Channel.signon4WS(systemID, domain, agencyID, userID, password);
        }

        public string signon(string agencyID, string userId, string password)
        {
            return base.Channel.signon(agencyID, userId, password);
        }

        public string authenticate(string userId, string ssoSessionId)
        {
            return base.Channel.authenticate(userId, ssoSessionId);
        }
    }
}
